### ISSUE TITLE
[Feat] - E-mails templates

### ISSUE THREAD

**Issue by mariano-aguero** [protofire/livepeer-alerts-frontend#7]
Design, must be:
- Clean and simple
- Responsive
- Mobile first design

Integrate HTML and CSS

Requires #2

**Comment by mgarciap** [comment]
There should be two versions.

### Happy version
You are alright, your transcoder [0xbd91c9..](https://explorer.livepeer.org/accounts/0xbd91c9df3c30f0e43b19b1dd05888cf9b647b781) made the reward call.
You've earned from inflation since Wednesday 26, 2018 00:00 am (rounds #1208 - #1209): *XX LPTs*


### Sad version
I am sorry, your transcoder [0xbd91c9..](https://explorer.livepeer.org/accounts/0xbd91c9df3c30f0e43b19b1dd05888cf9b647b781) missed the reward call.
You've earned from inflation since Wednesday 26, 2018 00:00 am (rounds #1208 - #1209): *XX LPTs*

**Comment by mariano-aguero** [comment]
See PR https://github.com/protofire/livepeer-alerts-backend/pull/13
